on:
  push:
    branches: main
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3.2.0
      - uses: actions/setup-java@v3.9.0
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.3.8'
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build apk --debug
