on:
  push:
    branches: main
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2.6.0
      - uses: actions/setup-java@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.17.6'
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build apk --debug
